modulesSettings:
  /home/pmlodawski/dev/projects/testgit/hello.luna:
    typeRepToVisMap: []
    breadcrumbsSettings:
    - - items: []
      - breadcrumbCameraSettings:
          logicalToScreen: ! '[[1.0,0.0,0.0,0.0],[0.0,1.0,0.0,0.0],[0.0,0.0,1.0,0.0],[0.0,0.0,0.0,1.0]]'
          screenToLogical: ! '[[1.0,0.0,0.0,0.0],[0.0,1.0,0.0,0.0],[0.0,0.0,1.0,0.0],[0.0,0.0,0.0,1.0]]'
          lastInverse: 0
